const SUPABASE_URL = "https://ivipigucanknjjvmnble.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2aXBpZ3VjYW5rbmpqdm1uYmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5MzAxNDQsImV4cCI6MjEwMjUwNjE0NH0.KnxywWhtiPgHOnAj5lUvu6K1LjTiOO3BfNfT7anech0";

export { SUPABASE_URL, SUPABASE_KEY };
