const SUPABASE_URL = "https://fnojavvttewlritnqgiz.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZub2phdnZ0dGV3bHJpdG5xZ2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwNTk5NjksImV4cCI6MjEwMTYzNTk2OX0.bjUiIN6oDlh4jBnwPNgaDDzGRG6GPj8O8yD4wlYjhFc";

export { SUPABASE_URL, SUPABASE_KEY };
